// Website translations
const siteTranslations = {
    en: {
        "t_0": "Chase Tag Arena",
        "t_1": "The ultimate local multiplayer tag arena. Apologize to your friends later.",
        "t_2": "Download on Google Play",
        "t_3": "Get Started Guide",
        "t_4": "Coming Soon to App Store",
        "t_5": "Game Features",
        "t_6": "8 Players Local",
        "t_7": "Connect up to 8 players! No need for extra controllers—everyone uses their own device as both a controller and a viewport for their personal perspective.",
        "t_8": "Totally Offline",
        "t_9": "Play anywhere, anytime. Chase Tag Arena requires",
        "t_10": "zero",
        "t_11": "internet connection. Just hop on the same local Wi-Fi or hotspot and start the chase.",
        "t_12": "TV Spectator Mode",
        "t_13": "Connect a TV or large screen to the host device for an epic cinematic view. Let spectators cheer on the action while you dominate the arena!",
        "t_14": "Level Editor",
        "t_15": "Build your own arenas with the powerful built-in editor. Place obstacles, traps, and power-ups anywhere—even while offline.",
        "t_16": "Cross-Platform",
        "t_17": "Play seamlessly on Phone, Tablet, PC, or Mac. Every device works together in the same arena.",
        "t_18": "Install the App",
        "t_19": "Download Chase Tag Arena from the Google Play Store on your favorite devices.",
        "t_20": "Join the Lobby",
        "t_21": "Make sure everyone is on the same Wi-Fi network. One player hosts a game, and others can join instantly.",
        "t_22": "Choose Your Arena",
        "t_23": "Select from our default professional maps or dive into the community's custom creations.",
        "t_24": "Run, Jump, Tag!",
        "t_25": "Use simple controls to outmaneuver your friends. First one to tag everyone wins!",
        "t_26": "Read the Full User Guide",
        "t_27": "User Guide",
        "t_28": "Privacy Policy",
        "t_29": "Terms of Service",
        "t_30": "App-Ads.txt",
        "t_31": "© 2026 Alex J. Chase Tag Arena and all associated assets are trademarks of the developer.",
        "t_32": "← Back to Home",
        "t_33": "Chase Tag Arena - Official User Guide",
        "t_34": "Welcome to Chase Tag Arena! The ultimate, fast-paced local multiplayer game where you outmaneuver your friends in intense games of tag. Because our game has some unique mechanics compared to traditional games, we've created this guide to get you up and running quickly.",
        "t_35": "1. What is Chase Tag Arena?",
        "t_36": "Chase Tag Arena is a",
        "t_37": "Local Area Network (LAN) Multiplayer",
        "t_38": "game. This means you don't connect to remote servers over the internet. Instead, you play directly with the friends who are in the same room (or on the same Wi-Fi network) as you. It's an \"offline multiplayer\" experience designed for zero-latency, high-energy fun.",
        "t_39": "Important:",
        "t_40": "All players",
        "t_41": "must",
        "t_42": "be connected to the exact same Wi-Fi network or mobile hotspot to play together.",
        "t_43": "2. Quick Start: Your First Match",
        "t_44": "Getting started is easy. As long as",
        "t_45": "one person",
        "t_46": "has downloaded the app, everyone else can join in!",
        "t_47": "For the Host (The person setting up the game):",
        "t_48": "Open the Chase Tag Arena App.",
        "t_49": "Tap the",
        "t_50": "\"HOST & PLAY\"",
        "t_51": "button.",
        "t_52": "Your device is now acting as the game server! You will see a Lobby screen with a QR code and a connection URL (e.g.,",
        "t_53": "http://192.168.1.5:3000",
        "t_54": "For the Players (Joining the game):",
        "t_55": "Ensure you are connected to the same Wi-Fi network as the Host.",
        "t_56": "If you have the app installed, open it and tap",
        "t_57": "\"JOIN ARENA\"",
        "t_58": ". It should automatically find the host!",
        "t_59": "Don't have the app? No problem!",
        "t_60": "Open the camera on your iOS or Android device and scan the QR code on the Host's screen. This will open the game directly in your web browser. (Note: You can also play on a PC/Mac by typing the connection URL into your browser).",
        "t_61": "Pro Tip:",
        "t_62": "While playing through the web browser works great, downloading the native app from the App Store or Google Play provides a significantly smoother, faster, and more robust experience compared to the browser-based Web App (PWA).",
        "t_63": "Adding Bots",
        "t_64": "Not enough players? Or just want more chaos? The Host can add AI bots to the game by pressing the",
        "t_65": "\"+ CHASER BOT\"",
        "t_66": "or",
        "t_67": "\"+ EVADER BOT\"",
        "t_68": "buttons in the lobby before starting the match.",
        "t_69": "3. Game Modes (Tag Types)",
        "t_70": "Chase Tag Arena features a variety of exciting tag types:",
        "t_71": "Classic:",
        "t_72": "One player starts as \"It\". Their goal is to tag another player to pass it on. The player who is \"It\" the least amount of time wins.",
        "t_73": "Zombie:",
        "t_74": "One player starts infected. Every player they tag also becomes infected. The last uninfected survivor wins!",
        "t_75": "Freeze:",
        "t_76": "Tagged evaders are frozen in place. Unfrozen evaders can touch frozen players to free them!",
        "t_77": "4. Rules, Powerups, and Objectives",
        "t_78": "Energy & Movement:",
        "t_79": "Use your device screen as a controller (joystick on the left, action buttons on the right) to move. Running slowly drains your energy. Sprinting drains it faster. You can't sprint without energy!",
        "t_80": "Tagging:",
        "t_81": "To tag someone, simply run into them while you are \"It\".",
        "t_82": "Powerups:",
        "t_83": "Keep an eye out for glowing items on the map! Collecting these can grant you an advantage:",
        "t_84": "Energy Refill (Green):",
        "t_85": "Instantly replenishes your energy so you can keep sprinting.",
        "t_86": "Invisibility (Purple):",
        "t_87": "Makes you mostly transparent to hide from opponents.",
        "t_88": "Speed (Red):",
        "t_89": "Gives you a temporary drastic boost in running speed.",
        "t_90": "Objectives:",
        "t_91": "Depending on the game mode, either avoid the \"It\" player at all costs or, if you are \"It\", hunt down the nearest player using the environment to cut them off.",
        "t_92": "5. The Arena Editor",
        "t_93": "Unleash your creativity with the built-in Arena Editor! You can access this from the main menu.",
        "t_94": "Build:",
        "t_95": "Set the size and then place walls, obstacles, portals and more, anywhere on the grid.",
        "t_96": "Save & Play:",
        "t_97": "Save your custom arenas offline and host them for your friends to play on.",
        "t_98": "Settings:",
        "t_99": "Inside the editor, you can adjust map bounds, lighting, and environmental effects to set the perfect mood for your chase.",
        "t_100": "For maximum control and speed of building, we highly suggest connecting with a PC/Mac and using a mouse and keyboard!",
        "t_101": "6. General Settings",
        "t_102": "From the main menu, tap the Settings icon to access customizable options:",
        "t_103": "JOYSTICK SENSITIVITY:",
        "t_104": "Adjust how fast your character turns and moves.",
        "t_105": "GRAPHICS:",
        "t_106": "Lower this setting to improve frame rates on older devices.",
        "t_107": "MUSIC VOLUME & SOUND EFFECTS:",
        "t_108": "Adjust background beats and sound effect volumes.",
        "t_109": "© 2026 Alex J. All rights reserved.",
        "t_110": "Last updated: March 27, 2026",
        "t_111": "1. Introduction",
        "t_112": "Welcome to Chase Tag Arena. We respect your privacy and are committed to protecting your personal data. This privacy policy will inform you as to how we look after your personal data when you use our game and tell you about your privacy rights and how the law protects you.",
        "t_113": "2. Data We Collect",
        "t_114": "Chase Tag Arena is designed to be a local multiplayer game. We do not collect any personal identification information (PII) from you. We do not require account creation or registration.",
        "t_115": "We may collect non-personal data such as device information (model, OS version) and gameplay statistics to help us improve the game experience.",
        "t_116": "3. Third-Party Services",
        "t_117": "We may use third-party services like Google Play Services for achievements, leaderboards, or cloud saves. These services may collect information used to identify you. Please refer to their respective privacy policies.",
        "t_118": "4. Children's Privacy",
        "t_119": "Our game is intended for a general audience. Since the game does not have any functionality to input, transmit, or store personal data, it is impossible for any user, including children, to provide us with personal information. We do not knowingly collect, nor are we technically able to receive, any personal data from children.",
        "t_120": "5. Offline Play",
        "t_121": "Chase Tag Arena is designed to work entirely offline. An internet connection is not required to play the game, host a local lobby, or use the level editor. Any data used for local multiplayer remains on your local network.",
        "t_122": "6. Contact Us",
        "t_123": "If you have any questions about this Privacy Policy, you can contact us via our developer page or community channels.",
        "t_124": "1. Acceptance of Terms",
        "t_125": "By downloading or using Chase Tag Arena, you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use the game.",
        "t_126": "2. License to Use",
        "t_127": "We grant you a personal, non-exclusive, non-transferable, limited license to use the game for your personal, non-commercial entertainment purposes only.",
        "t_128": "3. Restrictions",
        "t_129": "You may not: reverse engineer, decompile, or disassemble the game; use the game for any illegal purpose; or attempt to gain unauthorized access to any game systems.",
        "t_130": "4. Level Editor",
        "t_131": "If you use the Level Editor, you are responsible for the content you create. You agree not to create or share content that is offensive, infringing, or illegal.",
        "t_132": "5. Disclaimer of Warranties",
        "t_133": "The game is provided \"as is\" and \"as available\" without any warranties of any kind, whether express or implied.",
        "t_134": "6. Limitation of Liability",
        "t_135": "In no event shall Alex J be liable for any damages arising out of the use or inability to use the game."
    },
    no: {
        "t_0": "Chase Tag Arena",
        "t_1": "Den ultimate lokale flerspillerarenaen. Be vennene dine om unnskyldning senere.",
        "t_2": "Last ned på Google Play",
        "t_3": "Kom I Gang Guide",
        "t_4": "Kommer snart til App Store",
        "t_5": "Spillfunksjoner",
        "t_6": "8 Spillere Lokalt",
        "t_7": "Koble til opptil 8 spillere! Ingen ekstra kontrollere trengs—alle bruker sin egen enhet som både kontroller og skjerm.",
        "t_8": "Helt Offline",
        "t_9": "Spill hvor som helst, når som helst. Chase Tag Arena krever",
        "t_10": "null",
        "t_11": "internettforbindelse. Bare koble til samme lokale Wi-Fi og start jakten.",
        "t_12": "TV-Modus",
        "t_13": "Koble en TV eller storskjerm til vertsenheten for en episk filmatisk visning. La tilskuere heie på mens du dominerer arenaen!",
        "t_14": "Arena Redigerer",
        "t_15": "Bygg dine egne arenaer med den innebygde redigereren. Plasser hindringer og power-ups hvor som helst—selv offline.",
        "t_16": "På tvers av plattformer",
        "t_17": "Spill sømløst på Telefon, Nettbrett, PC, eller Mac. Hver enhet fungerer sammen i samme arena.",
        "t_18": "Installer Appen",
        "t_19": "Last ned Chase Tag Arena fra Google Play på dine favorittenheter.",
        "t_20": "Bli Med i Lobbyen",
        "t_21": "Sørg for at alle er på samme Wi-Fi-nettverk. Én spiller er vert, og andre kan bli med umiddelbart.",
        "t_22": "Velg Arena",
        "t_23": "Velg fra våre profesjonelle kart eller prøv fellesskapets egendefinerte kreasjoner.",
        "t_24": "Løp, Hopp, Tagg!",
        "t_25": "Bruk enkle kontroller for å utmanøvrere vennene dine. Førstemann til å ta alle vinner!",
        "t_26": "Les Hele Brukerveiledningen",
        "t_27": "Brukerveiledning",
        "t_28": "Personvernerklæring",
        "t_29": "Tjenestevilkår",
        "t_30": "App-Ads.txt",
        "t_31": "© 2026 Alex J. Alle rettigheter reservert.",
        "t_32": "← Tilbake til Hjem",
        "t_33": "Chase Tag Arena - Offisiell Brukerveiledning",
        "t_34": "Velkommen til Chase Tag Arena! Et raskt lokalt flerspillerspill hvor du utmanøvrerer vennene dine i intense runder med sisten. Fordi spillet vårt har unike mekanikker, har vi laget denne guiden for å få deg i gang raskt.",
        "t_35": "1. Hva er Chase Tag Arena?",
        "t_36": "Chase Tag Arena er et",
        "t_37": "Lokalt Nettverk (LAN) Flerspiller",
        "t_38": "spill. Du kobler ikke til servere over internett. I stedet spiller du direkte med vennene som er i samme rom (eller på samme Wi-Fi) som deg. En offline opplevelse designet for moro med null forsinkelse.",
        "t_39": "Viktig:",
        "t_40": "Alle spillere",
        "t_41": "må",
        "t_42": "være koblet til akkurat samme Wi-Fi-nettverk eller mobil hotspot for å spille sammen.",
        "t_43": "2. Hurtigstart: Din Første Kamp",
        "t_44": "Det er enkelt å komme i gang. Så lenge",
        "t_45": "én person",
        "t_46": "har lastet ned appen, kan alle andre bli med!",
        "t_47": "For Verten (Den som setter opp spillet):",
        "t_48": "Åpne Chase Tag Arena-appen.",
        "t_49": "Trykk på",
        "t_50": "\"VERT & SPILL\"",
        "t_51": "-knappen.",
        "t_52": "Enheten din fungerer nå som server! Du vil se en lobby med en QR-kode og en tilkoblings-URL (f.eks.",
        "t_53": "http://192.168.1.5:3000",
        "t_54": "For Spillerne (De som blir med i spillet):",
        "t_55": "Sørg for at du er koblet til samme Wi-Fi som verten.",
        "t_56": "Hvis du har appen, åpne den og trykk",
        "t_57": "\"BLI MED I ARENA\"",
        "t_58": ". Den skal automatisk finne verten!",
        "t_59": "Har du ikke appen? Ikke noe problem!",
        "t_60": "Åpne kameraet på mobilen din og skann QR-koden på vertens skjerm. Dette åpner spillet i nettleseren din.",
        "t_61": "Pro Tips:",
        "t_62": "Selv om det fungerer bra i nettleseren, gir det å laste ned appen en mye raskere og bedre opplevelse.",
        "t_63": "Legge til Boter",
        "t_64": "Ikke nok spillere? Verten kan legge til AI-boter ved å trykke på",
        "t_65": "\"+ JAGER BOT\"",
        "t_66": "eller",
        "t_67": "\"+ UNNVIKER BOT\"",
        "t_68": "knappene i lobbyen før kampen starter.",
        "t_69": "3. Spillmoduser (Typer Sisten)",
        "t_70": "Chase Tag Arena har flere spennende moduser:",
        "t_71": "Klassisk:",
        "t_72": "En spiller starter som den som \"har den\". Målet er å ta noen for å gi den videre.",
        "t_73": "Zombie:",
        "t_74": "Én spiller starter infisert. Alle de tar blir også infisert. Siste overlevende vinner!",
        "t_75": "Frys:",
        "t_76": "Tatte spillere fryses fast. Frie spillere kan ta på dem for å frigjøre dem!",
        "t_77": "4. Regler, Power-ups og Mål",
        "t_78": "Energi & Bevegelse:",
        "t_79": "Bruk skjermen som en kontroller. Å løpe tapper energi sakte. Sprinting tapper det raskere. Du kan ikke sprinte uten energi!",
        "t_80": "Tagging:",
        "t_81": "For å ta noen, bare løp inn i dem.",
        "t_82": "Power-ups:",
        "t_83": "Se etter lysende gjenstander på kartet! Disse gir fordeler:",
        "t_84": "Energipåfyll (Grønn):",
        "t_85": "Fyller opp energien din umiddelbart.",
        "t_86": "Usynlighet (Lilla):",
        "t_87": "Gjør deg nesten gjennomsiktig for å gjemme deg.",
        "t_88": "Fart (Rød):",
        "t_89": "Gir deg en midlertidig drastisk fartsøkning.",
        "t_90": "Mål:",
        "t_91": "Avhengig av modus, enten unngå jageren, eller jakt ned nærmeste spiller hvis du er jageren.",
        "t_92": "5. Arena Redigerer",
        "t_93": "Slipp kreativiteten løs! Du finner denne fra hovedmenyen.",
        "t_94": "Bygg:",
        "t_95": "Sett størrelsen og plasser vegger, hindringer og portaler hvor du vil.",
        "t_96": "Lagre & Spill:",
        "t_97": "Lagre dine egne arenaer offline og spill dem med venner.",
        "t_98": "Innstillinger:",
        "t_99": "Juster kartets grenser, belysning og effekter.",
        "t_100": "For maksimal kontroll anbefaler vi å koble til en PC/Mac og bruke mus og tastatur!",
        "t_101": "6. Generelle Innstillinger",
        "t_102": "Fra hovedmenyen, trykk på innstillingsikonet for alternativer:",
        "t_103": "JOYSTICK-FØLSOMHET:",
        "t_104": "Juster hvor raskt karakteren din snur seg og beveger seg.",
        "t_105": "GRAFIKK:",
        "t_106": "Senk denne innstillingen for bedre ytelse på eldre enheter.",
        "t_107": "MUSIKKVOLUM & LYDEFFEKTER:",
        "t_108": "Juster volumet for bakgrunnsmusikk og lydeffekter.",
        "t_109": "© 2026 Alex J. Alle rettigheter reservert.",
        "t_110": "Sist oppdatert: 27. mars 2026",
        "t_111": "1. Introduksjon",
        "t_112": "Velkommen til Chase Tag Arena. Vi respekterer ditt personvern.",
        "t_113": "2. Data Vi Samler Inn",
        "t_114": "Dette er et lokalt spill. Vi samler ikke inn noen personlig informasjon fra deg. Ingen konto er nødvendig.",
        "t_115": "Vi kan samle inn anonyme data som enhetsmodell og spillstatistikk for å forbedre spillet.",
        "t_116": "3. Tredjepartstjenester",
        "t_117": "Vi kan bruke tjenester som Google Play Spill for prestasjoner og ledertavler.",
        "t_118": "4. Barns Personvern",
        "t_119": "Spillet er for et generelt publikum og vi samler ikke inn data fra barn.",
        "t_120": "5. Offline Spill",
        "t_121": "Spillet fungerer helt offline. Ingen internettilkobling er nødvendig.",
        "t_122": "6. Kontakt Oss",
        "t_123": "Kontakt oss gjerne via vår utviklerside hvis du har spørsmål.",
        "t_124": "1. Aksept av Vilkår",
        "t_125": "Ved å bruke spillet godtar du disse vilkårene.",
        "t_126": "2. Lisens",
        "t_127": "Vi gir deg en begrenset lisens til å bruke spillet for personlig, ikke-kommersiell underholdning.",
        "t_128": "3. Restriksjoner",
        "t_129": "Du kan ikke dekompilere spillet eller bruke det ulovlig.",
        "t_130": "4. Arena Redigerer",
        "t_131": "Du er ansvarlig for innholdet du skaper.",
        "t_132": "5. Ansvarsfraskrivelse",
        "t_133": "Spillet leveres \"som det er\".",
        "t_134": "6. Ansvarsbegrensning",
        "t_135": "Utvikler er ikke ansvarlig for skader knyttet til bruk av spillet."
    },
    de: {
        "t_0": "Chase Tag Arena",
        "t_1": "Die ultimative lokale Multiplayer-Tag-Arena. Entschuldige dich später bei deinen Freunden.",
        "t_2": "Auf Google Play herunterladen",
        "t_3": "Erste Schritte",
        "t_4": "Bald im App Store",
        "t_5": "Spielfunktionen",
        "t_6": "8 Spieler Lokal",
        "t_7": "Verbinde bis zu 8 Spieler! Jeder nutzt sein eigenes Gerät als Controller und Bildschirm.",
        "t_8": "Vollständig Offline",
        "t_9": "Spiele überall. Chase Tag Arena benötigt",
        "t_10": "null",
        "t_11": "Internet. Verbindet euch einfach mit demselben WLAN und startet die Jagd.",
        "t_12": "TV-Modus",
        "t_13": "Verbinde einen TV oder großen Bildschirm mit dem Host-Gerät für eine epische Ansicht.",
        "t_14": "Arena Editor",
        "t_15": "Baue deine eigenen Arenen mit dem integrierten Editor.",
        "t_16": "Plattformübergreifend",
        "t_17": "Spiele nahtlos auf Smartphone, Tablet, PC oder Mac.",
        "t_18": "App Installieren",
        "t_19": "Lade Chase Tag Arena aus dem Google Play Store herunter.",
        "t_20": "Tritt der Lobby bei",
        "t_21": "Ein Spieler hostet das Spiel, und die anderen können sofort beitreten.",
        "t_22": "Wähle deine Arena",
        "t_23": "Wähle aus unseren professionellen Karten oder baue selbst.",
        "t_24": "Rennen, Springen, Fangen!",
        "t_25": "Der erste, der alle fängt, gewinnt!",
        "t_26": "Lies das vollständige Benutzerhandbuch",
        "t_27": "Benutzerhandbuch",
        "t_28": "Datenschutz",
        "t_29": "Nutzungsbedingungen",
        "t_30": "App-Ads.txt",
        "t_31": "© 2026 Alex J. Alle Rechte vorbehalten.",
        "t_32": "← Zurück zur Startseite",
        "t_33": "Chase Tag Arena - Offizielles Benutzerhandbuch",
        "t_34": "Willkommen bei Chase Tag Arena! Wir haben diesen Leitfaden erstellt, um dir den Einstieg zu erleichtern.",
        "t_35": "1. Was ist Chase Tag Arena?",
        "t_36": "Chase Tag Arena ist ein",
        "t_37": "Lokales Netzwerk (LAN) Multiplayer",
        "t_38": "Spiel. Du verbindest dich nicht mit Servern im Internet.",
        "t_39": "Wichtig:",
        "t_40": "Alle Spieler",
        "t_41": "müssen",
        "t_42": "im exakt selben WLAN-Netzwerk sein.",
        "t_43": "2. Schnellstart",
        "t_44": "Es ist ganz einfach. Solange",
        "t_45": "eine Person",
        "t_46": "die App heruntergeladen hat, können alle anderen beitreten!",
        "t_47": "Für den Host:",
        "t_48": "Öffne die Chase Tag Arena App.",
        "t_49": "Tippe auf den",
        "t_50": "\"HOSTEN & SPIELEN\"",
        "t_51": "-Button.",
        "t_52": "Dein Gerät fungiert nun als Spieleserver!",
        "t_53": "http://192.168.1.5:3000",
        "t_54": "Für die Spieler:",
        "t_55": "Stelle sicher, dass du mit demselben WLAN verbunden bist.",
        "t_56": "Wenn du die App hast, tippe auf",
        "t_57": "\"ARENA BEITRETEN\"",
        "t_58": ".",
        "t_59": "Hast du die App nicht? Kein Problem!",
        "t_60": "Scanne einfach den QR-Code mit deinem Handy. Das Spiel öffnet sich im Browser.",
        "t_61": "Pro-Tipp:",
        "t_62": "Das Herunterladen der nativen App bietet ein wesentlich flüssigeres Erlebnis.",
        "t_63": "Bots hinzufügen",
        "t_64": "Nicht genug Spieler? Drücke im Lobby-Menü auf",
        "t_65": "\"+ JÄGER BOT\"",
        "t_66": "oder",
        "t_67": "\"+ FLÜCHTENDER BOT\"",
        "t_68": ".",
        "t_69": "3. Spielmodi",
        "t_70": "Chase Tag Arena bietet verschiedene Modi:",
        "t_71": "Klassisch:",
        "t_72": "Ein Spieler beginnt als Fänger.",
        "t_73": "Zombie:",
        "t_74": "Ein infizierter Spieler startet.",
        "t_75": "Einfrieren:",
        "t_76": "Gefangene Spieler werden an Ort und Stelle eingefroren.",
        "t_77": "4. Regeln und Power-Ups",
        "t_78": "Energie:",
        "t_79": "Langsam laufen verbraucht Energie. Du kannst nicht ohne Energie sprinten!",
        "t_80": "Fangen:",
        "t_81": "Lauf einfach in andere Spieler hinein.",
        "t_82": "Power-Ups:",
        "t_83": "Achte auf leuchtende Gegenstände auf der Karte:",
        "t_84": "Energie (Grün):",
        "t_85": "Füllt deine Energie sofort wieder auf.",
        "t_86": "Unsichtbarkeit (Lila):",
        "t_87": "Macht dich größtenteils transparent.",
        "t_88": "Geschwindigkeit (Rot):",
        "t_89": "Gibt dir einen enormen Geschwindigkeitsschub.",
        "t_90": "Ziele:",
        "t_91": "Je nach Modus den Fänger meiden oder als Fänger alle anderen finden.",
        "t_92": "5. Arena Editor",
        "t_93": "Lass deiner Kreativität freien Lauf!",
        "t_94": "Bauen:",
        "t_95": "Platziere Wände, Hindernisse und mehr.",
        "t_96": "Speichern & Spielen:",
        "t_97": "Speichere deine Arenen und hoste sie für Freunde.",
        "t_98": "Einstellungen:",
        "t_99": "Passe Kartengrenzen und Beleuchtung an.",
        "t_100": "Wir empfehlen für den Editor eine Maus und Tastatur am PC!",
        "t_101": "6. Allgemeine Einstellungen",
        "t_102": "Passe dein Spiel an:",
        "t_103": "JOYSTICK-EMPFINDLICHKEIT:",
        "t_104": "Passe die Dreh- und Bewegungsgeschwindigkeit an.",
        "t_105": "GRAFIK:",
        "t_106": "Auf älteren Geräten reduzieren.",
        "t_107": "MUSIKLAUTSTÄRKE & SOUNDEFFEKTE:",
        "t_108": "Hintergrundmusik und Soundeffekte anpassen.",
        "t_109": "© 2026 Alex J. Alle Rechte vorbehalten.",
        "t_110": "Datenschutz",
        "t_111": "1. Einführung",
        "t_112": "Wir respektieren deine Privatsphäre.",
        "t_113": "2. Gesammelte Daten",
        "t_114": "Wir sammeln keine persönlichen Daten.",
        "t_115": "Wir sammeln möglicherweise nicht-personenbezogene Daten zur Fehlerbehebung.",
        "t_116": "3. Drittanbieter",
        "t_117": "Wir verwenden möglicherweise Google Play Services.",
        "t_118": "4. Kinder",
        "t_119": "Unser Spiel ist für alle Altersgruppen.",
        "t_120": "5. Offline Spielen",
        "t_121": "Das Spiel funktioniert vollständig offline.",
        "t_122": "6. Kontakt",
        "t_123": "Bei Fragen wende dich an unseren Entwicklerkanal.",
        "t_124": "1. Nutzungsbedingungen",
        "t_125": "Durch die Nutzung stimmst du unseren Bedingungen zu.",
        "t_126": "2. Lizenz",
        "t_127": "Wir gewähren dir eine persönliche Lizenz für das Spiel.",
        "t_128": "3. Einschränkungen",
        "t_129": "Das Dekompilieren oder illegale Nutzen ist untersagt.",
        "t_130": "4. Level Editor",
        "t_131": "Du bist für deine erstellten Inhalte verantwortlich.",
        "t_132": "5. Gewährleistungsausschluss",
        "t_133": "Das Spiel wird 'wie besehen' zur Verfügung gestellt.",
        "t_134": "6. Haftungsbeschränkung",
        "t_135": "Der Entwickler haftet nicht für Schäden."
    },
    fi: {
        "t_0": "Chase Tag Arena",
        "t_1": "Ultimaattinen paikallinen moninpeli. Pyydä anteeksi ystäviltäsi myöhemmin.",
        "t_2": "Lataa Google Playsta",
        "t_3": "Aloitusopas",
        "t_4": "Pian App Storessa",
        "t_5": "Pelin Ominaisuudet",
        "t_6": "8 Pelaajaa Paikallisesti",
        "t_7": "Yhdistä jopa 8 pelaajaa! Ette tarvitse erillisiä ohjaimia.",
        "t_8": "Täysin Offline",
        "t_9": "Pelaa missä vain, milloin vain. Chase Tag Arena vaatii",
        "t_10": "nolla",
        "t_11": "internetyhteyttä. Yhdistäkää vain samaan WiFi-verkkoon.",
        "t_12": "TV-tila",
        "t_13": "Yhdistä TV tai suuri näyttö isäntälaitteeseen.",
        "t_14": "Areena Editori",
        "t_15": "Rakenna omat areenasi sisäänrakennetulla editorilla.",
        "t_16": "Monialustainen",
        "t_17": "Pelaa saumattomasti puhelimella, tabletilla, PC:llä tai Macilla.",
        "t_18": "Asenna Sovellus",
        "t_19": "Lataa Chase Tag Arena Google Playsta.",
        "t_20": "Liity Aulaan",
        "t_21": "Varmista, että kaikki ovat samassa Wi-Fi-verkossa.",
        "t_22": "Valitse Areena",
        "t_23": "Valitse valmiista ammattilaisten kartoista.",
        "t_24": "Juokse, Hyppää, Ota Kiinni!",
        "t_25": "Ensimmäinen, joka saa kaikki kiinni, voittaa!",
        "t_26": "Lue koko Käyttöopas",
        "t_27": "Käyttöopas",
        "t_28": "Tietosuojakäytäntö",
        "t_29": "Palveluehdot",
        "t_30": "App-Ads.txt",
        "t_31": "© 2026 Alex J. Kaikki oikeudet pidätetään.",
        "t_32": "← Takaisin Kotiin",
        "t_33": "Chase Tag Arena - Virallinen Käyttöopas",
        "t_34": "Tervetuloa Chase Tag Arenaan!",
        "t_35": "1. Mikä on Chase Tag Arena?",
        "t_36": "Chase Tag Arena on",
        "t_37": "Paikallisen Verkon (LAN) Moninpeli",
        "t_38": "peli. Et yhdistä internetin palvelimiin.",
        "t_39": "Tärkeää:",
        "t_40": "Kaikkien pelaajien",
        "t_41": "täytyy",
        "t_42": "olla samassa Wi-Fi-verkossa.",
        "t_43": "2. Pika-aloitus",
        "t_44": "Aloittaminen on helppoa. Kunhan",
        "t_45": "yksi henkilö",
        "t_46": "on ladannut sovelluksen!",
        "t_47": "Isännälle:",
        "t_48": "Avaa Chase Tag Arena.",
        "t_49": "Paina",
        "t_50": "\"ISÄNNÖI & PELAA\"",
        "t_51": "-painiketta.",
        "t_52": "Laitteesi toimii nyt palvelimena!",
        "t_53": "http://192.168.1.5:3000",
        "t_54": "Pelaajille:",
        "t_55": "Varmista yhteys samaan Wi-Fiin.",
        "t_56": "Jos sinulla on sovellus, paina",
        "t_57": "\"LIITY AREENALLE\"",
        "t_58": ".",
        "t_59": "Eikö sinulla ole sovellusta? Ei hätää!",
        "t_60": "Skannaa QR-koodi kameralla.",
        "t_61": "Ammattilaisvinkki:",
        "t_62": "Sovelluksen lataaminen antaa paremman kokemuksen.",
        "t_63": "Bottien lisääminen",
        "t_64": "Eikö tarpeeksi pelaajia? Isäntä voi lisätä tekoälybotteja painamalla",
        "t_65": "\"+ JAAHTAJA BOTTI\"",
        "t_66": "tai",
        "t_67": "\"+ PAAKIJA BOTTI\"",
        "t_68": "ennen pelin alkua.",
        "t_69": "3. Pelimuodot",
        "t_70": "Chase Tag Arena tarjoaa erilaisia tiloja:",
        "t_71": "Klassinen:",
        "t_72": "Yksi pelaaja aloittaa hippana.",
        "t_73": "Zombie:",
        "t_74": "Yksi tartunnan saanut pelaaja aloittaa.",
        "t_75": "Freeze:",
        "t_76": "Kiinni saadut pelaajat jäätyvät.",
        "t_77": "4. Säännöt ja Powerupit",
        "t_78": "Energia:",
        "t_79": "Juokseminen kuluttaa energiaa.",
        "t_80": "Kiinniottaminen:",
        "t_81": "Juokse vain toista päin.",
        "t_82": "Powerupit:",
        "t_83": "Etsi hohtavia esineitä kartalta:",
        "t_84": "Energia (Vihreä):",
        "t_85": "Täyttää energiasi heti.",
        "t_86": "Näkymättömyys (Violetti):",
        "t_87": "Tekee sinusta melkein läpinäkyvän.",
        "t_88": "Nopeus (Punainen):",
        "t_89": "Antaa suuren nopeuden.",
        "t_90": "Tavoitteet:",
        "t_91": "Vältä hippaa tai ota kiinni kaikki.",
        "t_92": "5. Areena Editori",
        "t_93": "Päästä luovuutesi irti!",
        "t_94": "Rakenna:",
        "t_95": "Aseta seiniä, esteitä ja portaaleja.",
        "t_96": "Tallenna ja Pelaa:",
        "t_97": "Tallenna areenasi offline-tilassa.",
        "t_98": "Asetukset:",
        "t_99": "Säädä valaistusta ja tehosteita.",
        "t_100": "Suosittelemme hiirtä ja näppäimistöä!",
        "t_101": "6. Yleiset Asetukset",
        "t_102": "Muokkaa asetuksia:",
        "t_103": "OHJAIMEN HERKKYYS:",
        "t_104": "Säädä kääntymisen nopeutta.",
        "t_105": "GRAAFIIKKA:",
        "t_106": "Laske tätä vanhoilla laitteilla.",
        "t_107": "MUSIIKIN ÄÄNENVOIMAKKUUS & ÄÄNITEHOSTEET:",
        "t_108": "Säädä taustamusiikkia.",
        "t_109": "© 2026 Alex J. Kaikki oikeudet pidätetään.",
        "t_110": "Tietosuojakäytäntö",
        "t_111": "1. Esittely",
        "t_112": "Kunnioitamme yksityisyyttäsi.",
        "t_113": "2. Kerätyt tiedot",
        "t_114": "Emme kerää henkilötietoja.",
        "t_115": "Voimme kerätä ei-henkilökohtaista dataa.",
        "t_116": "3. Kolmannet osapuolet",
        "t_117": "Saatamme käyttää Google Play Servicesia.",
        "t_118": "4. Lapset",
        "t_119": "Peli on kaiken ikäisille.",
        "t_120": "5. Offline-peli",
        "t_121": "Peli toimii täysin offline-tilassa.",
        "t_122": "6. Yhteystiedot",
        "t_123": "Ota yhteyttä kehittäjän sivujen kautta.",
        "t_124": "1. Ehdot",
        "t_125": "Käyttämällä hyväksyt ehdot.",
        "t_126": "2. Lisenssi",
        "t_127": "Myönnämme henkilökohtaisen lisenssin.",
        "t_128": "3. Rajoitukset",
        "t_129": "Pelin purkaminen on kielletty.",
        "t_130": "4. Areena Editori",
        "t_131": "Olet vastuussa luomastasi sisällöstä.",
        "t_132": "5. Takuut",
        "t_133": "Peli tarjotaan sellaisenaan.",
        "t_134": "6. Vastuunrajoitus",
        "t_135": "Kehittäjä ei ole vastuussa vahingoista."
    },
    sv: {
        "t_0": "Chase Tag Arena",
        "t_1": "Den ultimata lokala multiplayer-arenan. Be dina vänner om ursäkt senare.",
        "t_2": "Ladda ner på Google Play",
        "t_3": "Kom Igång Guide",
        "t_4": "Kommer snart till App Store",
        "t_5": "Spelfunktioner",
        "t_6": "8 Spelare Lokalt",
        "t_7": "Anslut upp till 8 spelare! Inga extra handkontroller behövs.",
        "t_8": "Helt Offline",
        "t_9": "Spela var som helst. Chase Tag Arena kräver",
        "t_10": "noll",
        "t_11": "internetanslutning. Hoppa bara in på samma WiFi.",
        "t_12": "TV Läge",
        "t_13": "Anslut en TV till värdenheten för episk visning.",
        "t_14": "Arena Redigerare",
        "t_15": "Bygg dina egna arenor med den inbyggda redigeraren.",
        "t_16": "Cross-Platform",
        "t_17": "Spela sömlöst på Telefon, Surfplatta, PC eller Mac.",
        "t_18": "Installera Appen",
        "t_19": "Ladda ner Chase Tag Arena från Google Play.",
        "t_20": "Gå Med I Lobbyn",
        "t_21": "Se till att alla är på samma Wi-Fi-nätverk.",
        "t_22": "Välj Din Arena",
        "t_23": "Välj bland våra standardkartor.",
        "t_24": "Spring, Hoppa, Kulla!",
        "t_25": "Den första som kullar alla vinner!",
        "t_26": "Läs Hela Användarguiden",
        "t_27": "Användarguide",
        "t_28": "Integritetspolicy",
        "t_29": "Användarvillkor",
        "t_30": "App-Ads.txt",
        "t_31": "© 2026 Alex J. Alla rättigheter reserverade.",
        "t_32": "← Tillbaka till Hem",
        "t_33": "Chase Tag Arena - Officiell Användarguide",
        "t_34": "Välkommen till Chase Tag Arena!",
        "t_35": "1. Vad är Chase Tag Arena?",
        "t_36": "Chase Tag Arena är ett",
        "t_37": "Lokalt Nätverk (LAN) Multiplayer",
        "t_38": "spel. Du ansluter inte till servrar över internet.",
        "t_39": "Viktigt:",
        "t_40": "Alla spelare",
        "t_41": "måste",
        "t_42": "vara anslutna till exakt samma Wi-Fi-nätverk.",
        "t_43": "2. Snabbstart",
        "t_44": "Det är enkelt att komma igång. Så länge",
        "t_45": "en person",
        "t_46": "har laddat ner appen kan alla vara med!",
        "t_47": "För Värden:",
        "t_48": "Öppna Chase Tag Arena-appen.",
        "t_49": "Tryck på",
        "t_50": "\"VÄRD & SPELA\"",
        "t_51": "-knappen.",
        "t_52": "Din enhet fungerar nu som server!",
        "t_53": "http://192.168.1.5:3000",
        "t_54": "För Spelarna:",
        "t_55": "Se till att du är ansluten till samma Wi-Fi.",
        "t_56": "Om du har appen, tryck på",
        "t_57": "\"GÅ MED I ARENA\"",
        "t_58": ".",
        "t_59": "Har du inte appen? Inga problem!",
        "t_60": "Skanna QR-koden på värdens skärm med kameran.",
        "t_61": "Proffstips:",
        "t_62": "Att ladda ner appen ger en mycket smidigare upplevelse.",
        "t_63": "Lägga till Botar",
        "t_64": "Inte tillräckligt med spelare? Tryck på",
        "t_65": "\"+ JÄGAR BOT\"",
        "t_66": "eller",
        "t_67": "\"+ RYMMAR BOT\"",
        "t_68": "i lobbyn.",
        "t_69": "3. Spellägen",
        "t_70": "Olika kulltyper:",
        "t_71": "Klassisk:",
        "t_72": "En spelare börjar som jägare.",
        "t_73": "Zombie:",
        "t_74": "En infekterad spelare börjar.",
        "t_75": "Freeze:",
        "t_76": "Tagna rymmare fryser fast.",
        "t_77": "4. Regler och Powerups",
        "t_78": "Energi:",
        "t_79": "Att springa dränerar din energi.",
        "t_80": "Kullning:",
        "t_81": "Spring bara in i dem.",
        "t_82": "Powerups:",
        "t_83": "Håll utkik efter lysande föremål:",
        "t_84": "Energi (Grön):",
        "t_85": "Fyller på din energi direkt.",
        "t_86": "Osynlighet (Lila):",
        "t_87": "Gör dig nästan genomskinlig.",
        "t_88": "Hastighet (Röd):",
        "t_89": "Ger dig en enorm fartökning.",
        "t_90": "Mål:",
        "t_91": "Undvik jägaren eller jaga ner alla.",
        "t_92": "5. Arena Redigerare",
        "t_93": "Släpp loss din kreativitet!",
        "t_94": "Bygg:",
        "t_95": "Placera hinder, väggar och portaler.",
        "t_96": "Spara & Spela:",
        "t_97": "Spara dina arenor offline.",
        "t_98": "Inställningar:",
        "t_99": "Justera ljus och effekter.",
        "t_100": "Vi föreslår att du använder PC/Mac med mus!",
        "t_101": "6. Generella Inställningar",
        "t_102": "Från huvudmenyn:",
        "t_103": "JOYSTICK-KÄNSLIGHET:",
        "t_104": "Justera hur snabbt du rör dig.",
        "t_105": "GRAFIK:",
        "t_106": "Sänk detta på äldre enheter.",
        "t_107": "MUSIKVOLYM & LJUDEFFEKTER:",
        "t_108": "Justera ljudet.",
        "t_109": "© 2026 Alex J. Alla rättigheter reserverade.",
        "t_110": "Integritetspolicy",
        "t_111": "1. Introduktion",
        "t_112": "Vi respekterar din integritet.",
        "t_113": "2. Data Vi Samlar In",
        "t_114": "Vi samlar inte in någon personlig data.",
        "t_115": "Endast anonym data kan samlas in för förbättringar.",
        "t_116": "3. Tredjepartstjänster",
        "t_117": "Vi kan använda Google Play Services.",
        "t_118": "4. Barns Integritet",
        "t_119": "Spelet samlar inte in data från barn.",
        "t_120": "5. Offline Spel",
        "t_121": "Fungerar helt offline.",
        "t_122": "6. Kontakta Oss",
        "t_123": "Kontakta utvecklaren.",
        "t_124": "1. Accept av Villkor",
        "t_125": "Genom att använda appen godkänner du villkoren.",
        "t_126": "2. Licens",
        "t_127": "Begränsad, personlig licens.",
        "t_128": "3. Restriktioner",
        "t_129": "Du får inte reverse engineera spelet.",
        "t_130": "4. Arena Redigerare",
        "t_131": "Du ansvarar för innehållet du skapar.",
        "t_132": "5. Garantifriskrivning",
        "t_133": "Erbjuds i befintligt skick.",
        "t_134": "6. Ansvarsbegränsning",
        "t_135": "Skaparen ansvarar inte för skador."
    },
    da: { "t_50": "\"VÆRT & SPIL\"", "t_57": "\"TILSLUT ARENA\"", "t_65": "\"+ JÆGER BOT\"", "t_67": "\"+ FLYGTNING BOT\"", "t_71": "Klassisk:", "t_73": "Zombie:", "t_75": "Frys:", "t_103": "JOYSTICK-FØLSOMHET:", "t_105": "GRAFIK:" },
    it: { "t_50": "\"OSPITA & GIOCA\"", "t_57": "\"UNISCITI ALL'ARENA\"", "t_65": "\"+ BOT INSEGUITORE\"", "t_67": "\"+ BOT FUGGITIVO\"", "t_71": "Classico:", "t_73": "Zombie:", "t_75": "Ghiaccio:", "t_103": "SENSIBILITÀ JOYSTICK:", "t_105": "GRAFICA:" },
    es: { "t_50": "\"ORGANIZAR Y JUGAR\"", "t_57": "\"UNIRSE A LA ARENA\"", "t_65": "\"+ CAZADOR BOT\"", "t_67": "\"+ EVASOR BOT\"", "t_71": "Clásico:", "t_73": "Zombi:", "t_75": "Congelar:", "t_103": "SENSIBILIDAD JOYSTICK:", "t_105": "GRÁFICOS:" }
};

function getDeviceLang() {
    try {
        if (localStorage.getItem('langOverride')) return localStorage.getItem('langOverride');
        let lang = (navigator.language || navigator.userLanguage || 'en').substring(0, 2).toLowerCase()
        if (lang === 'nb' || lang === 'nn') lang = 'no'
        return siteTranslations[lang] ? lang : 'en'
    } catch(e) {
        return 'en'
    }
}

function applyTranslations() {
    document.querySelectorAll('[data-i18n]').forEach(el => {
        const key = el.getAttribute('data-i18n');
        // fallback logic inside siteTranslations or English
        const langDict = siteTranslations[currentLang] || siteTranslations['en'];
        let translation = langDict[key] || siteTranslations['en'][key];
        if (translation) {
            el.textContent = translation;
        }
    });
    
    const selector = document.getElementById('lang-selector');
    if (selector) {
        selector.value = currentLang;
    }
}

function changeLanguage(lang) {
    currentLang = lang;
    localStorage.setItem('langOverride', lang);
    applyTranslations();
}

let currentLang = 'en';

document.addEventListener('DOMContentLoaded', () => {
    currentLang = getDeviceLang();
    
    // Create language selector if it doesn't exist
    if (!document.getElementById('lang-selector')) {
        const selectorContainer = document.createElement('div');
        selectorContainer.style.position = 'absolute';
        selectorContainer.style.top = '20px';
        selectorContainer.style.right = '20px';
        selectorContainer.style.zIndex = '9999';
        
        const selectorHTML = \`
            <select id="lang-selector" onchange="changeLanguage(this.value)" style="padding: 8px; border-radius: 8px; background: rgba(0,0,0,0.7); color: white; border: 1px solid rgba(255,255,255,0.3); cursor: pointer; font-family: 'Fredoka', sans-serif; font-size: 14px; outline: none; backdrop-filter: blur(5px);">
                <option value="en">English</option>
                <option value="no">Norsk</option>
                <option value="de">Deutsch</option>
                <option value="fi">Suomi</option>
                <option value="sv">Svenska</option>
                <option value="da">Dansk</option>
                <option value="it">Italiano</option>
                <option value="es">Español</option>
            </select>
        \`;
        selectorContainer.innerHTML = selectorHTML;
        document.body.appendChild(selectorContainer);
    }
    
    applyTranslations();
});
